#!/usr/bin/env perl
use warnings;
use strict;

my $got = qx(seq-fix-start seq-fix-start/dnaN-rc-plus.ffn);
my $expected = ">A0A1Q3YLB1_131-246 SUBSTR:0,408
ACCCTGCCCCAGAAGCAGCTGAAGCACCTGTTCCACATGGTGCACTTCGCCATGGCCCAGCAGGACATCAGGTACTACCT
GAACGGCCTGCTGCTGGTGACCGACGGCGCCCAGGTGAGGGTGGTGGCCACCGACGGCCACAGGCTGGCCCTGTGCGAGG
CCACCGTGGAGGGCGCCGAGCTGGCCAGGCAGGAGGTGATCATCCCCAGGAAGACCGTGCTGGAGCTGCAGAGGCTGCTG
GCCGACAGCGACGACCCCGTGCTGATCGACGTGAGCGGCAACCAGGTGAGGTTCAGGTTCGGCGAGGTGGAGATGATCAG
CAAGCTGGTGGAGGGCAAGTTCCCCGACtttttttttttttttttttttttttttttttttttttttttttttttttttt
ttttttttaaaaaaaaaaaa
";
die "seq-fix-start failed" unless $got eq $expected;
